/* Международные единицы измерения, включенные в ОКЕИ */

/* Единицы длины */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'003', N'Миллиметр', N'мм', N'mm', N'ММ', N'MMT', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'004', N'Сантиметр', N'см', N'cm', N'СМ', N'CMT', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'005', N'Дециметр', N'дм', N'dm', N'ДМ', N'DMT', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'006', N'Метр', N'м', N'm', N'М', N'MTR', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'008', N'Километр; тысяча метров', N'км; 10³ м', N'km', N'КМ; ТЫС М', N'KMT', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'009', N'Мегаметр; миллион метров', N'Мм; 10⁶ м', N'Mm', N'МЕГАМ; МЛН М', N'MAM', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'039', N'Дюйм (25,4 мм)', N'дюйм', N'in', N'ДЮЙМ', N'INH', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'041', N'Фут (0,3048 м)', N'фут', N'ft', N'ФУТ', N'FOT', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'043', N'Ярд (0,9144 м)', N'ярд', N'yd', N'ЯРД', N'YRD', 1)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'047', N'Морская миля (1852 м)', N'миля', N'n mile', N'МИЛЬ', N'NMI', 1)

/* Единицы площади */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'050', N'Квадратный миллиметр', N'мм²', N'mm²', N'ММ2', N'MMK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'051', N'Квадратный сантиметр', N'см²', N'cm²', N'СМ2', N'CMK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'053', N'Квадратный дециметр', N'дм²', N'dm²', N'ДМ2', N'DMK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'055', N'Квадратный метр', N'м²', N'm²', N'М2', N'MTK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'058', N'Тысяча квадратных метров', N'10³ м²', N'daa', N'ТЫС М2', N'DAA', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'059', N'Гектар', N'га', N'ha', N'ГА', N'HAR', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'061', N'Квадратный километр', N'км²', N'km²', N'КМ2', N'KMK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'071', N'Квадратный дюйм (645,16 мм²)', N'дюйм²', N'in²', N'ДЮЙМ2', N'INK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'073', N'Квадратный фут (0,092903 м²)', N'фут²', N'ft²', N'ФУТ2', N'FTK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'075', N'Квадратный ярд (0,8361274 м²)', N'ярд²', N'yd²', N'ЯРД2', N'YDK', 2)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'109', N'Ар (100 м²)', N'а', N'a', N'АР', N'ARE', 2)

/* Единицы объема */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'110', N'Кубический миллиметр', N'мм³', N'mm³', N'ММ3', N'MMQ', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'111', N'Кубический сантиметр; миллилитр', N'см³; мл', N'cm³; ml', N'СМ3; МЛ', N'CMQ; MLT', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'112', N'Кубический дециметр; литр', N'дм³; л', N'dm³; I; L', N'ДМ3; Л', N'DMQ; LTR', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'113', N'Кубический метр', N'м³', N'm³', N'М3', N'MTQ', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'118', N'Децилитр', N'дл', N'dl', N'ДЛ', N'DLT', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'122', N'Гектолитр', N'гл', N'hl', N'ГЛ', N'HLT', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'126', N'Мегалитр', N'Мл', N'Ml', N'МЕГАЛ', N'MAL', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'131', N'Кубический дюйм (16387,1 мм³)', N'дюйм³', N'in³', N'ДЮЙМ3', N'INQ', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'132', N'Кубический фут (0,02831685 м³)', N'фут³', N'ft³', N'ФУТ3', N'FTQ', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'133', N'Кубический ярд (0,764555 м³)', N'ярд³', N'yd³', N'ЯРД3', N'YDQ', 3)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'159', N'Миллион кубических метров', N'10⁶ м³', N'10⁶ m³', N'МЛН М3', N'HMQ', 3)

/* Единицы массы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'160', N'Гектограмм', N'гг', N'hg', N'ГГ', N'HGM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'161', N'Миллиграмм', N'мг', N'mg', N'МГ', N'MGM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'162', N'Метрический карат', N'кар', N'МС', N'КАР', N'CTM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'163', N'Грамм', N'г', N'g', N'Г', N'GRM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'164', N'Микрограмм', N'мкг', N'mg', N'МКГ', N'MG', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'166', N'Килограмм', N'кг', N'kg', N'КГ', N'KGM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'168', N'Тонна; метрическая тонна (1000 кг)', N'т', N't', N'Т', N'TNE', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'170', N'Килотонна', N'10³ т', N'kt', N'КТ', N'KTN', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'173', N'Сантиграмм', N'сг', N'cg', N'СГ', N'CGM', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'181', N'Брутто-регистровая тонна (2,8316 м3)', N'БРТ', N'-', N'БРУТТ. РЕГИСТР Т', N'GRT', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'185', N'Грузоподъемность в метрических тоннах', N'т грп', N'-', N'Т ГРУЗОПОД', N'CCT', 4)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'206', N'Центнер (метрический) (100 кг); гектокилограмм; квинтал1 (метрический); децитонна', N'ц', N'q; 10² kg', N'Ц', N'DTN', 4)

/* Технические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'212', N'Ватт', N'Вт', N'W', N'ВТ', N'WTT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'214', N'Киловатт', N'кВт', N'kW', N'КВТ', N'KWT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'215', N'Мегаватт; тысяча киловатт', N'МВт; 10³ кВт', N'MW', N'МЕГАВТ; ТЫС КВТ', N'MAW', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'222', N'Вольт', N'В', N'V', N'В', N'VLT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'223', N'Киловольт', N'кВ', N'kV', N'КВ', N'KVT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'227', N'Киловольт-ампер', N'кВ·А', N'kV·А', N'КВ·А', N'KVA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'228', N'Мегавольт-ампер (тысяча киловольт-ампер)', N'МВ·А', N'МV·А', N'МЕГАВ·А', N'MVA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'230', N'Киловар', N'квар', N'kVAR', N'КВАР', N'KVR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'243', N'Ватт-час', N'Вт·ч', N'W·h', N'ВТ·Ч', N'WHR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'245', N'Киловатт-час', N'кВт·ч', N'kW·h', N'КВТ·Ч', N'KWH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'246', N'Мегаватт-час; 1000 киловатт-часов', N'МВт·ч; 10³ кВт·ч', N'МW·h', N'МЕГАВТ·Ч; ТЫС КВТ·Ч', N'MWH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'247', N'Гигаватт-час (миллион киловатт-часов)', N'ГВт·ч', N'GW·h', N'ГИГАВТ·Ч', N'GWH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'260', N'Ампер', N'А', N'A', N'А', N'AMP', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'263', N'Ампер-час (3,6 кКл)', N'А·ч', N'А·h', N'А·Ч', N'AMH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'264', N'Тысяча ампер-часов', N'10³ А·ч', N'10³ А·h', N'ТЫС А·Ч', N'TAH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'270', N'Кулон', N'Кл', N'C', N'КЛ', N'COU', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'271', N'Джоуль', N'Дж', N'J', N'ДЖ', N'JOU', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'273', N'Килоджоуль', N'кДж', N'kJ', N'КДЖ', N'KJO', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'274', N'Ом', N'Ом', N'Ω', N'ОМ', N'OHM', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'276', N'Грей', N'Гр', N'Gy', N'ГР', N'GY', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'277', N'Микрогрей', N'мкГр', N'μGy', N'МКГР', N'MKGY', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'278', N'Миллигрей', N'мГр', N'mGy', N'МЛГР', N'MGY', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'279', N'Килогрей', N'кГр', N'kGy', N'КИЛОГР', N'KGY', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'280', N'Градус Цельсия', N'°C', N'°C', N'ГРАД ЦЕЛЬС', N'CEL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'281', N'Градус Фаренгейта', N'°F', N'°F', N'ГРАД ФАРЕНГ', N'FAN', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'282', N'Кандела', N'кд', N'cd', N'КД', N'CDL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'283', N'Люкс', N'лк', N'lx', N'ЛК', N'LUX', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'284', N'Люмен', N'лм', N'lm', N'ЛМ', N'LUM', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'288', N'Кельвин', N'К', N'K', N'К', N'KEL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'289', N'Ньютон', N'Н', N'N', N'Н', N'NEW', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'290', N'Герц', N'Гц', N'Hz', N'ГЦ', N'HTZ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'291', N'Килогерц', N'кГц', N'kHz', N'КГЦ', N'KHZ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'292', N'Мегагерц', N'МГц', N'MHz', N'МЕГАГЦ', N'MHZ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'293', N'Гигагерц', N'ГГц', N'GHz', N'ГИГАГЦ', N'GHZ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'294', N'Паскаль', N'Па', N'Pa', N'ПА', N'PAL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'295', N'Терагерц', N'ТГц', N'THz', N'ТЕРАГЦ', N'THZ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'296', N'Сименс', N'См', N'S', N'СИ', N'SIE', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'297', N'Килопаскаль', N'кПа', N'kPa', N'КПА', N'KPA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'298', N'Мегапаскаль', N'МПа', N'MPa', N'МЕГАПА', N'MPA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'300', N'Физическая атмосфера (101325 Па)', N'атм', N'atm', N'АТМ', N'ATM', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'301', N'Техническая атмосфера (98066,5 Па)', N'ат', N'at', N'АТТ', N'ATT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'302', N'Гигабеккерель', N'ГБк', N'GBq', N'ГИГАБК', N'GBQ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'303', N'Килобеккерель', N'кБк', N'kBq', N'КИЛОБК', N'KBQ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'304', N'Милликюри', N'мКи', N'mCi', N'МКИ', N'MCU', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'305', N'Кюри', N'Ки', N'Ci', N'КИ', N'CUR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'306', N'Грамм делящихся изотопов', N'г Д/И', N'g fissile isotopes', N'Г ДЕЛЯЩ ИЗОТОП', N'GFI', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'307', N'Мегабеккерель', N'МБк', N'MBq', N'МЕГАБК', N'MBQ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'308', N'Миллибар', N'мб', N'mbar', N'МБАР', N'MBR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'309', N'Бар', N'бар', N'bar', N'БАР', N'BAR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'310', N'Гектобар', N'гб', N'hbar', N'ГБАР', N'HBA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'312', N'Килобар', N'кб', N'kbar', N'КБАР', N'KBA', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'314', N'Фарад', N'Ф', N'F', N'Ф', N'FAR', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'316', N'Килограмм на кубический метр', N'кг/м³', N'kg/m³', N'КГ/М3', N'KMQ', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'318', N'Зиверт', N'Зв', N'Sv', N'ЗВ', N'SV', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'319', N'Микрозиверт', N'мкЗв', N'μSv', N'МКЗВ', N'MKSV', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'320', N'Моль', N'моль', N'mol', N'МОЛЬ', N'MOL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'321', N'Миллизиверт', N'мЗв', N'mSv', N'МЗВ', N'MSV', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'323', N'Беккерель', N'Бк', N'Bq', N'БК', N'BQL', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'324', N'Вебер', N'Вб', N'Wb', N'ВБ', N'WEB', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'327', N'Узел (миля/ч)', N'уз', N'kn', N'УЗ', N'KNT', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'328', N'Метр в секунду', N'м/с', N'm/s', N'М/С', N'MTS', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'330', N'Оборот в секунду', N'об/с', N'r/s', N'ОБ/С', N'RPS', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'331', N'Оборот в минуту', N'об/мин', N'r/min', N'ОБ/МИН', N'RPM', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'333', N'Километр в час', N'км/ч', N'km/h', N'КМ/Ч', N'KMH', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'335', N'Метр на секунду в квадрате', N'м/с²', N'm/s²', N'М/С2', N'MSK', 5)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'349', N'Кулон на килограмм', N'Кл/кг', N'C/kg', N'КЛ/КГ', N'CKG', 5)

/* Единицы времени */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'354', N'Секунда', N'с', N's', N'С', N'SEC', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'355', N'Минута', N'мин', N'min', N'МИН', N'MIN', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'356', N'Час', N'ч', N'h', N'Ч', N'HUR', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'359', N'Сутки', N'сут; дн', N'd', N'СУТ; ДН', N'DAY', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'360', N'Неделя', N'нед', N'-', N'НЕД', N'WEE', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'361', N'Декада', N'дек', N'-', N'ДЕК', N'DAD', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'362', N'Месяц', N'мес', N'-', N'МЕС', N'MON', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'364', N'Квартал', N'кварт', N'-', N'КВАРТ', N'QAN', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'365', N'Полугодие', N'полгода', N'-', N'ПОЛГОД', N'SAN', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'366', N'Год', N'г; лет', N'a', N'ГОД; ЛЕТ', N'ANN', 6)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'368', N'Десятилетие', N'деслет', N'-', N'ДЕСЛЕТ', N'DEC', 6)

/* Экономические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'499', N'Килограмм в секунду', N'кг/с', N'—', N'КГ/С', N'KGS', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'533', N'Тонна пара в час', N'т пар/ч', N'—', N'Т ПАР/Ч', N'TSH', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'596', N'Кубический метр в секунду', N'м³/с', N'm³/s', N'М3/С', N'MQS', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'598', N'Кубический метр в час', N'м³/ч', N'm³/h', N'М3/Ч', N'MQH', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'599', N'Тысяча кубических метров в сутки', N'10³ м³/сут', N'—', N'ТЫС М3/СУТ', N'TQD', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'616', N'Бобина', N'боб', N'—', N'БОБ', N'NBB', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'625', N'Лист', N'л.', N'—', N'ЛИСТ', N'LEF', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'626', N'Сто листов', N'100 л.', N'—', N'100 ЛИСТ', N'CLF', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'630', N'Тысяча стандартных условных кирпичей', N'тыс. станд. усл. кирп', N'—', N'ТЫС СТАНД УСЛ КИРП', N'MBE', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'641', N'Дюжина (12 шт.)', N'дюжина', N'Doz; 12', N'ДЮЖИНА', N'DZN', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'657', N'Изделие', N'изд', N'—', N'ИЗД', N'NAR', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'683', N'Сто ящиков', N'100 ящ', N'Hbx', N'100 ЯЩ', N'HBX', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'704', N'Набор', N'набор', N'—', N'НАБОР', N'SET', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'715', N'Пара (2 шт.)', N'пар', N'pr; 2', N'ПАР', N'NPR', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'730', N'Два десятка', N'20', N'20', N'2 ДЕС', N'SCO', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'732', N'Десять пар', N'10 пар', N'—', N'ДЕС ПАР', N'TPR', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'733', N'Дюжина пар', N'дюжина пар', N'—', N'ДЮЖИНА ПАР', N'DPR', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'734', N'Посылка', N'посыл', N'—', N'ПОСЫЛ', N'NPL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'735', N'Часть', N'часть', N'—', N'ЧАСТЬ', N'NPT', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'736', N'Рулон', N'рул', N'—', N'РУЛ', N'NRL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'737', N'Дюжина рулонов', N'дюжина рул', N'—', N'ДЮЖИНА РУЛ', N'DRL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'740', N'Дюжина штук', N'дюжина шт', N'—', N'ДЮЖИНА ШТ', N'DPC', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'745', N'Элемент', N'элем', N'CI', N'ЭЛЕМ', N'NCL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'778', N'Упаковка', N'упак', N'—', N'УПАК', N'NMP', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'780', N'Дюжина упаковок', N'дюжина упак', N'—', N'ДЮЖИНА УПАК', N'DZP', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'781', N'Сто упаковок', N'100 упак', N'—', N'100 УПАК', N'CNP', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'796', N'Штука', N'шт', N'pc; 1', N'ШТ', N'PCE; NMB', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'797', N'Сто штук', N'100 шт', N'100', N'100 ШТ', N'CEN', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'798', N'Тысяча штук', N'тыс. шт; 1000 шт', N'1000', N'ТЫС ШТ', N'MIL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'799', N'Миллион штук', N'10⁶ шт', N'10⁶', N'МЛН ШТ', N'MIO', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'800', N'Миллиард штук', N'10⁹ шт', N'10⁹', N'МЛРД ШТ', N'MLD', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'801', N'Биллион штук (Европа); триллион штук', N'10¹² шт', N'10¹²', N'БИЛЛ ШТ (ЕВР); ТРИЛЛ ШТ', N'BIL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'802', N'Квинтильон штук (Европа)', N'10¹⁸ шт', N'10¹⁸', N'КВИНТ ШТ', N'TRL', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'820', N'Крепость спирта по массе', N'креп. спирта по массе', N'% mds', N'КРЕП СПИРТ ПО МАСС', N'ASM', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'821', N'Крепость спирта по объему', N'креп. спирта по объему', N'% vol', N'КРЕП СПИРТ ПО ОБЪЕМ', N'ASV', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'831', N'Литр чистого (100%) спирта', N'л 100% спирта', N'—', N'Л ЧИСТ СПИРТ', N'LPA', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'833', N'Гектолитр чистого (100%) спирта', N'Гл 100% спирта', N'—', N'ГЛ ЧИСТ СПИРТ', N'HPA', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'841', N'Килограмм пероксида водорода', N'кг H₂О₂', N'—', N'КГ ПЕРОКСИД ВОДОРОДА', N'—', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'845', N'Килограмм 90%-го сухого вещества', N'кг 90% с/в', N'—', N'КГ 90 ПРОЦ СУХ ВЕЩ', N'KSD', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'847', N'Тонна 90%-го сухого вещества', N'т 90% с/в', N'—', N'Т 90 ПРОЦ СУХ ВЕЩ', N'TSD', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'852', N'Килограмм оксида калия', N'кг К₂О', N'—', N'КГ ОКСИД КАЛИЯ', N'KPO', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'859', N'Килограмм гидроксида калия', N'кг КОН', N'—', N'КГ ГИДРОКСИД КАЛИЯ', N'KPH', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'861', N'Килограмм азота', N'кг N', N'—', N'КГ АЗОТ', N'KNI', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'863', N'Килограмм гидроксида натрия', N'кг NaOH', N'—', N'КГ ГИДРОКСИД НАТРИЯ', N'KSH', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'865', N'Килограмм пятиокиси фосфора', N'кг Р₂О₅', N'—', N'КГ ПЯТИОКИСЬ ФОСФОРА', N'KPP', 7)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [SymbolEn], [AlphaRu], [AlphaEn], [GroupId]) VALUES (N'867', N'Килограмм урана', N'кг U', N'—', N'КГ УРАН', N'KUR', 7)


/* Национальные единицы измерения, включенные в ОКЕИ */

/* Единицы длины */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'018', N'Погонный метр', N'пог. м', N'ПОГ М', 8)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'019', N'Тысяча погонных метров', N'10³ пог. м', N'ТЫС ПОГ М', 8)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'020', N'Условный метр', N'усл. м', N'УСЛ М', 8)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'048', N'Тысяча условных метров', N'10³ усл. м', N'ТЫС УСЛ М', 8)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'049', N'Километр условных труб', N'км усл. труб', N'КМ УСЛ ТРУБ', 8)

/* Единицы площади */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'054', N'Тысяча квадратных дециметров', N'10³ дм²', N'ТЫС ДМ2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'056', N'Миллион квадратных дециметров', N'10⁶ дм²', N'МЛН ДМ2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'057', N'Миллион квадратных метров', N'10⁶ м²', N'МЛН М2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'060', N'Тысяча гектаров', N'10³ га', N'ТЫС ГА', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'062', N'Условный квадратный метр', N'усл. м²', N'УСЛ М2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'063', N'Тысяча условных квадратных метров', N'10³ усл. м²', N'ТЫС УСЛ М2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'064', N'Миллион условных квадратных метров', N'10⁶ усл. м²', N'МЛН УСЛ М2', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'081', N'Квадратный метр общей площади', N'м² общ. пл', N'М2 ОБЩ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'082', N'Тысяча квадратных метров общей площади', N'10³ м² общ. пл', N'ТЫС М2 ОБЩ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'083', N'Миллион квадратных метров общей площади', N'10⁶ м² общ. пл', N'МЛН М2 ОБЩ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'084', N'Квадратный метр жилой площади', N'м² жил. пл', N'М2 ЖИЛ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'085', N'Тысяча квадратных метров жилой площади', N'10³ м² жил. пл', N'ТЫС М2 ЖИЛ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'086', N'Миллион квадратных метров жилой площади', N'10⁶ м² жил. пл', N'МЛН М2 ЖИЛ ПЛ', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'087', N'Квадратный метр учебно-лабораторных зданий', N'м² уч. лаб. здан', N'М2 УЧ. ЛАБ ЗДАН', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'088', N'Тысяча квадратных метров учебно-лабораторных зданий', N'10³ м² уч. лаб. здан', N'ТЫС М2 УЧ. ЛАБ ЗДАН', 9)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'089', N'Миллион квадратных метров в двухмиллиметровом исчислении', N'10⁶ м² 2 мм исч', N'МЛН М2 2ММ ИСЧ', 9)

/* Единицы объема */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'114', N'Тысяча кубических метров', N'10³ м³', N'ТЫС М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'115', N'Миллиард кубических метров', N'10⁹ м³', N'МЛРД М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'116', N'Декалитр', N'дкл', N'ДКЛ', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'119', N'Тысяча декалитров', N'10³ дкл', N'ТЫС ДКЛ', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'120', N'Миллион декалитров', N'10⁶ дкл', N'МЛН ДКЛ', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'121', N'Плотный кубический метр', N'плотн. м³', N'ПЛОТН М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'123', N'Условный кубический метр', N'усл. м³', N'УСЛ М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'124', N'Тысяча условных кубических метров', N'10³ усл. м³', N'ТЫС УСЛ М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'125', N'Миллион кубических метров переработки газа', N'10⁶ м³ перераб. газа', N'МЛН М3 ПЕРЕРАБ ГАЗА', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'127', N'Тысяча плотных кубических метров', N'10³ плотн. м³', N'ТЫС ПЛОТН М3', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'128', N'Тысяча полулитров', N'10³ пол. л', N'ТЫС ПОЛ Л', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'129', N'Миллион полулитров', N'10⁶ пол. л', N'МЛН ПОЛ Л', 10)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'130', N'Тысяча литров; 1000 литров', N'10³ л; 1000 л', N'ТЫС Л', 10)

/* Единицы массы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'165', N'Тысяча каратов метрических', N'10³ кар', N'ТЫС КАР', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'167', N'Миллион каратов метрических', N'10⁶ кар', N'МЛН КАР', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'169', N'Тысяча тонн', N'10³ т', N'ТЫС Т', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'171', N'Миллион тонн', N'10⁶ т', N'МЛН Т', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'172', N'Тонна условного топлива', N'т усл. топл', N'Т УСЛ ТОПЛ', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'175', N'Тысяча тонн условного топлива', N'10³ т усл. топл', N'ТЫС Т УСЛ ТОПЛ', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'176', N'Миллион тонн условного топлива', N'10⁶ т усл. топл', N'МЛН Т УСЛ ТОПЛ', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'177', N'Тысяча тонн единовременного хранения', N'10³ т единовр. хран', N'ТЫС Т ЕДИНОВР ХРАН', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'178', N'Тысяча тонн переработки', N'10³ т перераб', N'ТЫС Т ПЕРЕРАБ', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'179', N'Условная тонна', N'усл. т', N'УСЛ Т', 11)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'207', N'Тысяча центнеров', N'10³ ц', N'ТЫС Ц', 11)

/* Технические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'226', N'Вольт-ампер', N'В·А', N'В·А', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'231', N'Метр в час', N'м/ч', N'М/Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'232', N'Килокалория', N'ккал', N'ККАЛ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'233', N'Гигакалория', N'Гкал', N'ГИГАКАЛ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'234', N'Тысяча гигакалорий', N'10³ Гкал', N'ТЫС ГИГАКАЛ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'235', N'Миллион гигакалорий', N'10⁶ Гкал', N'МЛН ГИГАКАЛ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'236', N'Калория в час', N'кал/ч', N'КАЛ/Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'237', N'Килокалория в час', N'ккал/ч', N'ККАЛ/Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'238', N'Гигакалория в час', N'Гкал/ч', N'ГИГАКАЛ/Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'239', N'Тысяча гигакалорий в час', N'10³ Гкал/ч', N'ТЫС ГИГАКАЛ/Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'241', N'Миллион ампер-часов', N'10⁶ А·ч', N'МЛН А·Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'242', N'Миллион киловольт-ампер', N'10⁶ кВ·А', N'МЛН КВ·А', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'248', N'Киловольт-ампер реактивный', N'кВ·А Р', N'КВ·А Р', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'249', N'Миллиард киловатт-часов', N'10⁹ кВт·ч', N'МЛРД КВТ·Ч', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'250', N'Тысяча киловольт-ампер реактивных', N'10³ кВ·А Р', N'ТЫС КВ·А Р', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'251', N'Лошадиная сила', N'л. с', N'ЛС', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'252', N'Тысяча лошадиных сил', N'10³ л. с', N'ТЫС ЛС', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'253', N'Миллион лошадиных сил', N'10⁶ л. с', N'МЛН ЛС', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'254', N'Бит', N'бит', N'БИТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'255', N'Байт', N'байт', N'БАЙТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'256', N'Килобайт', N'кбайт', N'КБАЙТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'257', N'Мегабайт', N'Мбайт', N'МБАЙТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'258', N'Бод', N'бод', N'БОД', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'287', N'Генри', N'Гн', N'ГН', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'313', N'Тесла', N'Тл', N'ТЛ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'317', N'Килограмм на квадратный сантиметр', N'кг/см²', N'КГ/СМ2', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'337', N'Миллиметр водяного столба', N'мм вод. ст', N'ММ ВОД СТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'338', N'Миллиметр ртутного столба', N'мм рт. ст', N'ММ РТ СТ', 12)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'339', N'Сантиметр водяного столба', N'см вод. ст', N'СМ ВОД СТ', 12)

/* Единицы времени */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'348', N'Фемтосекунда', N'фс', N'ФС', 13)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'350', N'Пикосекунда', N'пс', N'ПС', 13)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'351', N'Наносекунда', N'нс', N'НС', 13)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'352', N'Микросекунда', N'мкс', N'МКС', 13)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'353', N'Миллисекунда', N'млс', N'МЛС', 13)

/* Экономические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'383', N'Рубль', N'руб', N'РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'384', N'Тысяча рублей', N'10³ руб', N'ТЫС РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'385', N'Миллион рублей', N'10⁶ руб', N'МЛН РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'386', N'Миллиард рублей', N'10⁹ руб', N'МЛРД РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'387', N'Триллион рублей', N'10¹² руб', N'ТРИЛЛ РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'388', N'Квадрильон рублей', N'10¹⁵ руб', N'КВАДР РУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'414', N'Пассажиро-километр', N'пасс·км', N'ПАСС·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'421', N'Пассажирское место (пассажирских мест)', N'пасс. мест', N'ПАСС. МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'423', N'Тысяча пассажиро-километров', N'10³ пасс·км', N'ТЫС ПАСС·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'424', N'Миллион пассажиро-километров', N'10⁶ пасс·км', N'МЛН ПАСС·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'427', N'Пассажиропоток', N'пасс. поток', N'ПАСС. ПОТОК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'449', N'Тонно-километр', N'т·км', N'Т·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'450', N'Тысяча тонно-километров', N'10³ т·км', N'ТЫС Т·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'451', N'Миллион тонно-километров', N'10⁶ т·км', N'МЛН Т·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'479', N'Тысяча наборов', N'10³ набор', N'ТЫС НАБОР', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'508', N'Тысяча метров кубических в час', N'10³ м3/ч', N'ТЫС М3/Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'509', N'Километр в сутки', N'км/сут', N'КМ/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'510', N'Грамм на киловатт-час', N'г/кВт·ч', N'Г/КВТ·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'511', N'Килограмм на гигакалорию', N'кг/Гкал', N'КГ/ГИГАКАЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'512', N'Тонно-номер', N'т·ном', N'Т·НОМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'513', N'Автотонна', N'авто т', N'АВТО Т', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'514', N'Тонна тяги', N'т тяги', N'Т ТЯГИ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'515', N'Дедвейт-тонна', N'дедвейт·т', N'ДЕДВЕЙТ·Т', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'516', N'Тонно-танид', N'т·танид', N'Т·ТАНИД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'521', N'Человек на квадратный метр', N'чел/м2', N'ЧЕЛ/М2', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'522', N'Человек на квадратный километр', N'чел/км2', N'ЧЕЛ/КМ2', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'534', N'Тонна в час', N'т/ч', N'Т/Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'535', N'Тонна в сутки', N'т/сут', N'Т/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'536', N'Тонна в смену', N'т/смен', N'Т/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'537', N'Тысяча тонн в сезон', N'10³ т/сез', N'ТЫС Т/СЕЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'538', N'Тысяча тонн в год', N'10³ т/год', N'ТЫС Т/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'539', N'Человеко-час', N'чел·ч', N'ЧЕЛ·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'540', N'Человеко-день', N'чел·дн', N'ЧЕЛ·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'541', N'Тысяча человеко-дней', N'10³ чел·дн', N'ТЫС ЧЕЛ·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'542', N'Тысяча человеко-часов', N'10³ чел·ч', N'ТЫС ЧЕЛ·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'543', N'Тысяча условных банок в смену', N'10³ усл. банк/смен', N'ТЫС УСЛ БАНК/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'544', N'Миллион единиц в год', N'10⁶ ед/год', N'МЛН ЕД/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'545', N'Посещение в смену', N'посещ/смен', N'ПОСЕЩ/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'546', N'Тысяча посещений в смену', N'10³ посещ/смен', N'ТЫС ПОСЕЩ/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'547', N'Пара в смену', N'пар/смен', N'ПАР/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'548', N'Тысяча пар в смену', N'10³ пар/смен', N'ТЫС ПАР/СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'550', N'Миллион тонн в год', N'10⁶ т/год', N'МЛН Т/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'552', N'Тонна переработки в сутки', N'т перераб/сут', N'Т ПЕРЕРАБ/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'553', N'Тысяча тонн переработки в сутки', N'10³ т перераб/сут', N'ТЫС Т ПЕРЕРАБ/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'554', N'Центнер переработки в сутки', N'ц перераб/сут', N'Ц ПЕРЕРАБ/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'555', N'Тысяча центнеров переработки в сутки', N'10³ ц перераб/сут', N'ТЫС Ц ПЕРЕРАБ/СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'556', N'Тысяча голов в год', N'10³ гол/год', N'ТЫС ГОЛ/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'557', N'Миллион голов в год', N'10⁶ гол/год', N'МЛН ГОЛ/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'558', N'Тысяча птицемест', N'10³ птицемест', N'ТЫС ПТИЦЕМЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'559', N'Тысяча кур-несушек', N'10³ кур. несуш', N'ТЫС КУР. НЕСУШ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'561', N'Тысяча тонн пара в час', N'10³ т пар/ч', N'ТЫС Т ПАР/Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'562', N'Тысяча прядильных веретен', N'10³ пряд. верет', N'ТЫС ПРЯД ВЕРЕТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'563', N'Тысяча прядильных мест', N'10³ пряд. мест', N'ТЫС ПРЯД МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'639', N'Доза', N'доз', N'ДОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'640', N'Тысяча доз', N'10³ доз', N'ТЫС ДОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'642', N'Единица', N'ед', N'ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'643', N'Тысяча единиц', N'10³ ед', N'ТЫС ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'644', N'Миллион единиц', N'10⁶ ед', N'МЛН ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'661', N'Канал', N'канал', N'КАНАЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'673', N'Тысяча комплектов', N'10³ компл', N'ТЫС КОМПЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'698', N'Место', N'мест', N'МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'699', N'Тысяча мест', N'10³ мест', N'ТЫС МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'709', N'Тысяча номеров', N'10³ ном', N'ТЫС НОМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'724', N'Тысяча гектаров порций', N'10³ га порц', N'ТЫС ГА ПОРЦ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'728', N'Пачка', N'пач', N'ПАЧ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'729', N'Тысяча пачек', N'10³ пач', N'ТЫС ПАЧ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'744', N'Процент', N'%', N'ПРОЦ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'746', N'Промилле (0,1 процента)', N'‰', N'ПРОМИЛЛЕ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'751', N'Тысяча рулонов', N'10³ рул', N'ТЫС РУЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'761', N'Тысяча станов', N'10³ стан', N'ТЫС СТАН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'762', N'Станция', N'станц', N'СТАНЦ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'775', N'Тысяча тюбиков', N'10³ тюбик', N'ТЫС ТЮБИК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'776', N'Тысяча условных тубов', N'10³ усл. туб', N'ТЫС УСЛ ТУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'779', N'Миллион упаковок', N'10⁶ упак', N'МЛН УПАК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'782', N'Тысяча упаковок', N'10³ упак', N'ТЫС УПАК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'792', N'Человек', N'чел', N'ЧЕЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'793', N'Тысяча человек', N'10³ чел', N'ТЫС ЧЕЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'794', N'Миллион человек', N'10⁶ чел', N'МЛН ЧЕЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'808', N'Миллион экземпляров', N'10⁶ экз', N'МЛН ЭКЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'810', N'Ячейка', N'яч', N'ЯЧ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'812', N'Ящик', N'ящ', N'ЯЩ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'836', N'Голова', N'гол', N'ГОЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'837', N'Тысяча пар', N'10³ пар', N'ТЫС ПАР', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'838', N'Миллион пар', N'10⁶ пар', N'МЛН ПАР', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'839', N'Комплект', N'компл', N'КОМПЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'840', N'Секция', N'секц', N'СЕКЦ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'868', N'Бутылка', N'бут', N'БУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'869', N'Тысяча бутылок', N'10³ бут', N'ТЫС БУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'870', N'Ампула', N'ампул', N'АМПУЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'871', N'Тысяча ампул', N'10³ ампул', N'ТЫС АМПУЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'872', N'Флакон', N'флак', N'ФЛАК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'873', N'Тысяча флаконов', N'10³ флак', N'ТЫС ФЛАК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'874', N'Тысяча тубов', N'10³ туб', N'ТЫС ТУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'875', N'Тысяча коробок', N'10³ кор', N'ТЫС КОР', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'876', N'Условная единица', N'усл. ед', N'УСЛ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'877', N'Тысяча условных единиц', N'10³ усл. ед', N'ТЫС УСЛ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'878', N'Миллион условных единиц', N'10⁶ усл. ед', N'МЛН УСЛ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'879', N'Условная штука', N'усл. шт', N'УСЛ ШТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'880', N'Тысяча условных штук', N'10³ усл. шт', N'ТЫС УСЛ ШТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'881', N'Условная банка', N'усл. банк', N'УСЛ БАНК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'882', N'Тысяча условных банок', N'10³ усл. банк', N'ТЫС УСЛ БАНК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'883', N'Миллион условных банок', N'10⁶ усл. банк', N'МЛН УСЛ БАНК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'884', N'Условный кусок', N'усл. кус', N'УСЛ КУС', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'885', N'Тысяча условных кусков', N'10³ усл. кус', N'ТЫС УСЛ КУС', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'886', N'Миллион условных кусков', N'10⁶ усл. кус', N'МЛН УСЛ КУС', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'887', N'Условный ящик', N'усл. ящ', N'УСЛ ЯЩ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'888', N'Тысяча условных ящиков', N'10³ усл. ящ', N'ТЫС УСЛ ЯЩ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'889', N'Условная катушка', N'усл. кат', N'УСЛ КАТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'890', N'Тысяча условных катушек', N'10³ усл. кат', N'ТЫС УСЛ КАТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'891', N'Условная плитка', N'усл. плит', N'УСЛ ПЛИТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'892', N'Тысяча условных плиток', N'10³ усл. плит', N'ТЫС УСЛ ПЛИТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'893', N'Условный кирпич', N'усл. кирп', N'УСЛ КИРП', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'894', N'Тысяча условных кирпичей', N'10³ усл. кирп', N'ТЫС УСЛ КИРП', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'895', N'Миллион условных кирпичей', N'10⁶ усл. кирп', N'МЛН УСЛ КИРП', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'896', N'Семья', N'семей', N'СЕМЕЙ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'897', N'Тысяча семей', N'10³ семей', N'ТЫС СЕМЕЙ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'898', N'Миллион семей', N'10⁶ семей', N'МЛН СЕМЕЙ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'899', N'Домохозяйство', N'домхоз', N'ДОМХОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'900', N'Тысяча домохозяйств', N'10³ домхоз', N'ТЫС ДОМХОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'901', N'Миллион домохозяйств', N'10⁶ домхоз', N'МЛН ДОМХОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'902', N'Ученическое место', N'учен. мест', N'УЧЕН МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'903', N'Тысяча ученических мест', N'10³ учен. мест', N'ТЫС УЧЕН МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'904', N'Рабочее место', N'раб. мест', N'РАБ МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'905', N'Тысяча рабочих мест', N'10³ раб. мест', N'ТЫС РАБ МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'906', N'Посадочное место', N'посад. мест', N'ПОСАД МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'907', N'Тысяча посадочных мест', N'10³ посад. мест', N'ТЫС ПОСАД МЕСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'908', N'Номер', N'ном', N'НОМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'909', N'Квартира', N'кварт', N'КВАРТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'910', N'Тысяча квартир', N'10³ кварт', N'ТЫС КВАРТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'911', N'Койка', N'коек', N'КОЕК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'912', N'Тысяча коек', N'10³ коек', N'ТЫС КОЕК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'913', N'Том книжного фонда', N'том книжн. фонд', N'ТОМ КНИЖН ФОНД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'914', N'Тысяча томов книжного фонда', N'10³ том книжн. фонд', N'ТЫС ТОМ КНИЖН ФОНД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'915', N'Условный ремонт', N'усл. рем', N'УСЛ РЕМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'916', N'Условный ремонт в год', N'усл. рем/год', N'УСЛ РЕМ/ГОД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'917', N'Смена', N'смен', N'СМЕН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'918', N'Лист авторский', N'л. авт', N'ЛИСТ АВТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'920', N'Лист печатный', N'л. печ', N'ЛИСТ ПЕЧ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'921', N'Лист учетно-издательский', N'л. уч.-изд', N'ЛИСТ УЧ.ИЗД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'922', N'Знак', N'знак', N'ЗНАК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'923', N'Слово', N'слово', N'СЛОВО', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'924', N'Символ', N'символ', N'СИМВОЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'925', N'Условная труба', N'усл. труб', N'УСЛ ТРУБ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'930', N'Тысяча пластин', N'10³ пласт', N'ТЫС ПЛАСТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'937', N'Миллион доз', N'10⁶ доз', N'МЛН ДОЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'949', N'Миллион листов-оттисков', N'10⁶ лист·оттиск', N'МЛН ЛИСТ ОТТИСК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'950', N'Вагоно (машино)-день', N'ваг (маш)·дн', N'ВАГ (МАШ)·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'951', N'Тысяча вагоно (машино)-часов', N'10³ ваг (маш)·ч', N'ТЫС ВАГ (МАШ)·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'952', N'Тысяча вагоно (машино)-километров', N'10³ ваг (маш)·км', N'ТЫС ВАГ (МАШ)·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'953', N'Тысяча место-километров', N'10³ мест·км', N'ТЫС МЕСТ·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'954', N'Вагоно-сутки', N'ваг·сут', N'ВАГ·СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'955', N'Тысяча поездо-часов', N'10³ поезд·ч', N'ТЫС ПОЕЗД·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'956', N'Тысяча поездо-километров', N'10³ поезд·км', N'ТЫС ПОЕЗД·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'957', N'Тысяча тонно-миль', N'10³ т·миль', N'ТЫС Т·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'958', N'Тысяча пассажиро-миль', N'10³ пасс·миль', N'ТЫС ПАСС·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'959', N'Автомобиле-день', N'автомоб·дн', N'АВТОМОБ·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'960', N'Тысяча автомобиле-тонно-дней', N'10³ автомоб·т·дн', N'ТЫС АВТОМОБ·Т·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'961', N'Тысяча автомобиле-часов', N'10³ автомоб·ч', N'ТЫС АВТОМОБ·Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'962', N'Тысяча автомобиле-место-дней', N'10³ автомоб·мест·дн', N'ТЫС АВТОМОБ·МЕСТ·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'963', N'Приведенный час', N'привед. ч', N'ПРИВЕД. Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'964', N'Самолето-километр', N'самолет·км', N'САМОЛЕТ·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'965', N'Тысяча километров', N'10³ км', N'ТЫС КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'966', N'Тысяча тоннаже-рейсов', N'10³ тоннаж·рейс', N'ТЫС ТОННАЖ·РЕЙС', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'967', N'Миллион тонно-миль', N'10⁶ т·миль', N'МЛН Т·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'968', N'Миллион пассажиро-миль', N'10⁶ пасс·миль', N'МЛН ПАСС·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'969', N'Миллион тоннаже-миль', N'10⁶ тоннаж·миль', N'МЛН ТОННАЖ·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'970', N'Миллион пассажиро-место-миль', N'10⁶ пасс·мест·миль', N'МЛН ПАСС·МЕСТ·МИЛЬ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'971', N'Кормо-день', N'корм·дн', N'КОРМ·ДН', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'972', N'Центнер кормовых единиц', N'ц корм ед', N'Ц КОРМ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'973', N'Тысяча автомобиле-километров', N'10³ автомоб·км', N'ТЫС АВТОМОБ·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'974', N'Тысяча тоннаже-суток', N'10³ тоннаж·сут', N'ТЫС ТОННАЖ·СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'975', N'Суго-сутки', N'суго·сут', N'СУГО·СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'976', N'Штука в 20-футовом эквиваленте (ДФЭ)', N'штук в 20-футовом эквиваленте', N'ШТ В 20 ФУТ ЭКВИВ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'977', N'Канало-километр', N'канал·км', N'КАНАЛ·КМ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'978', N'Канало-концы', N'канал·конц', N'КАНАЛ·КОНЦ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'979', N'Тысяча экземпляров', N'10³ экз', N'ТЫС ЭКЗ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'980', N'Тысяча долларов', N'10³ доллар', N'ТЫС ДОЛЛАР', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'981', N'Тысяча тонн кормовых единиц', N'10³ корм ед', N'ТЫС Т КОРМ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'982', N'Миллион тонн кормовых единиц', N'10⁶ корм ед', N'МЛН Т КОРМ ЕД', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'983', N'Судо-сутки', N'суд·сут', N'СУД·СУТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'984', N'Центнеров с гектара', N'ц/га', N'Ц/ГА', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'985', N'Тысяча голов', N'10³ гол', N'ТЫС ГОЛ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'986', N'Тысяча краско-оттисков', N'10³ краск·оттиск', N'ТЫС КРАСК ОТТИСК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'987', N'Миллион краско-оттисков', N'10⁶ краск·оттиск', N'МЛН КРАСК ОТТИСК', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'988', N'Миллион условных плиток', N'10⁶ усл. плит', N'МЛН УСЛ ПЛИТ', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'989', N'Человек в час', N'чел/ч', N'ЧЕЛ/Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'990', N'Пассажиров в час', N'пасс/ч', N'ПАСС/Ч', 14)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'991', N'Пассажиро-миля', N'пасс·миля', N'ПАСС МИЛЯ', 14)


/* Четырехзначные национальные единицы измерения, включенные в ОКЕИ */

/* Технические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2311', N'Грей в секунду', N'Гр/с', N'ГР/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2312', N'Грей в минуту', N'Гр/мин', N'ГР/МИН', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2313', N'Грей в час', N'Гр/ч', N'ГР/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2314', N'Микрогрей в секунду', N'мкГр/с', N'МКГР/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2315', N'Микрогрей в час', N'мкГр/ч', N'МКГР/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2316', N'Миллигрей в час', N'мГр/ч', N'МЛГР/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2351', N'Зиверт в час', N'Зв/ч', N'ЗВ/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2352', N'Микрозиверт в секунду', N'мкЗв/с', N'МКЗВ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2353', N'Микрозиверт в час', N'мкЗв/ч', N'МКЗВ/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2354', N'Миллизиверт в час', N'мЗв/ч', N'МЛЗВ/Ч', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2541', N'Бит в секунду', N'бит/с', N'БИТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2543', N'Килобит в секунду', N'кбит/с', N'КБИТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2545', N'Мегабит в секунду', N'Мбит/с', N'МБИТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2547', N'Гигабит в секунду', N'Гбит/с', N'ГБИТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2551', N'Байт в секунду', N'Байт/с', N'БАЙТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2552', N'Гигабайт в секунду', N'Гбайт/с', N'ГБАЙТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2553', N'Гигабайт', N'Гбайт', N'ГБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2554', N'Терабайт', N'Тбайт', N'ТБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2555', N'Петабайт', N'Пбайт', N'ПБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2556', N'Эксабайт', N'Эбайт', N'ЭБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2557', N'Зеттабайт', N'Збайт', N'ЗБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2558', N'Йоттабайт', N'Йбайт', N'ЙБАЙТ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2561', N'Килобайт в секунду', N'кбайт/с', N'КБАЙТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2571', N'Мегабайт в секунду', N'Мбайт/с', N'МБАЙТ/С', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2581', N'Эрланг', N'Эрл', N'ЭРЛАНГ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'2931', N'Гигагерц', N'ГГц', N'ГИГАГЦ', 15)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'3135', N'Децибел', N'дБ', N'ДЕЦИБЕЛ', 15)

/* Экономические единицы */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'3831', N'Рубль тонна', N'руб. тонна', N'РУБ ТОННА', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'5401', N'Дето-день', N'дет·дн', N'ДЕТ ДН', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'5423', N'Человек в год', N'чел/год', N'ЧЕЛ/ГОД', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'5451', N'Посещение', N'посещ', N'ПОСЕЩ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'5562', N'Тысяча гнезд', N'10³ гнезд', N'ТЫС ГНЕЗД', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'6421', N'Единиц в год', N'ед/год', N'ЕД/ГОД', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'6422', N'Вызов', N'вызов', N'ВЫЗОВ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'6423', N'Посевная единица', N'пос. ед', N'ПОС ЕД', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'6424', N'Штамм', N'штамм', N'ШТАММ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'7923', N'Абонент', N'Абонент', N'АБОНЕНТ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'8361', N'Особь', N'ос', N'ОСОБЬ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'8751', N'Коробка', N'кор', N'КОР', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9061', N'Миллион гектаров', N'10⁶ га', N'МЛН ГА', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9062', N'Миллиард гектаров', N'10⁹ га', N'МЛРД ГА', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9111', N'Койко-день', N'койк·дн', N'КОЙК ДН', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9113', N'Пациенто-день', N'пациент·дн', N'ПАЦИЕНТ ДН', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9245', N'Запись', N'запись', N'ЗАПИСЬ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9246', N'Документ', N'докум', N'ДОКУМ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9491', N'Лист-оттиск', N'лист·оттиск', N'ЛИСТ ОТТИСК', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9501', N'Вагоно (машино)-час', N'ваг (маш)·ч', N'ВАГ (МАШ)·Ч', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9557', N'Миллион голов', N'10⁶ гол', N'МЛН ГОЛ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9641', N'Летный час', N'летн. ч', N'ЛЕТН Ч', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9642', N'Балл', N'балл', N'БАЛЛ', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9802', N'Миллион долларов', N'10⁶ доллар', N'МЛН ДОЛЛАР', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9803', N'Миллиард долларов', N'10⁹ доллар', N'МЛРД ДОЛЛАР', 16)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9805', N'Доллар за тонну', N'доллар за тонну', N'ДОЛЛАР ЗА ТОННУ', 16)

/* Дозировки лекарственных препаратов */
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9910', N'Международная единица биологической активности', N'МЕ', N'МЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9911', N'Тысяча международных единиц биологической активности', N'тыс. МЕ', N'ТЫС. МЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9912', N'Миллион международных единиц биологической активности', N'млн. МЕ', N'МЛН. МЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9913', N'Международная единица биологической активности на грамм', N'МЕ/г', N'МЕ/Г', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9914', N'Тысяча международных единиц биологической активности на грамм', N'тыс. МЕ/г', N'ТЫС. МЕ/Г', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9915', N'Миллион международных единиц биологической активности на грамм', N'млн. МЕ/г', N'МЛН. МЕ/Г', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9916', N'Международная единица биологической активности на миллилитр', N'МЕ/мл', N'МЕ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9917', N'Тысяча международных единиц биологической активности на миллилитр', N'тыс. МЕ/мл', N'ТЫС. МЕ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9918', N'Миллион международных единиц биологической активности на миллилитр', N'млн. МЕ/мл', N'МЛН. МЕ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9920', N'Единица действия биологической активности', N'ЕД', N'ЕД', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9921', N'Единица действия биологической активности на грамм', N'ЕД/г', N'ЕД/Г', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9922', N'Тысяча единиц действия биологической активности на грамм', N'тыс. ЕД/г', N'ТЫС. ЕД/Г', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9923', N'Единица действия биологической активности на микролитр', N'ЕД/мкл', N'ЕД/МКЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9924', N'Единица действия биологической активности на миллилитр', N'ЕД/мл', N'ЕД/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9925', N'Тысяча единиц действия биологической активности на миллилитр', N'тыс. ЕД/мл', N'ТЫС. ЕД/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9926', N'Миллион единиц действия биологической активности на миллилитр', N'млн. ЕД/мл', N'МЛН. ЕД/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9927', N'Единица действия биологической активности в сутки', N'ЕД/сут', N'ЕД/СУТ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9930', N'Антитоксическая единица', N'АЕ', N'АЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9931', N'Тысяча антитоксических единиц', N'тыс. АЕ', N'ТЫС. АЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9940', N'Антитрипсиновая единица', N'АТрЕ', N'АТРЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9941', N'Тысяча антитрипсиновых единиц', N'тыс. АТрЕ', N'ТЫС. АТРЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9950', N'Индекс Реактивности', N'ИР', N'ИР', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9951', N'Индекс Реактивности на миллилитр', N'ИР/мл', N'ИР/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9960', N'Килобеккерель на миллилитр', N'кБк/мл', N'КИЛОБК/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9961', N'Мегабеккерель на миллилитр', N'МБк/мл', N'МЕГАБК/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9962', N'Мегабеккерель на метр квадратный', N'МБк/м²', N'МЕГАБК/М2', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9970', N'Калликреиновая ингибирующая единица на миллилитр', N'КИЕ/мл', N'КИЕ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9971', N'Тысяча калликреиновых ингибирующих единиц на миллилитр', N'тыс. КИЕ/мл', N'ТЫС. КИЕ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9980', N'Миллион колониеобразуюших единиц', N'млн. КОЕ', N'МЛН. КОЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9981', N'Миллион колониеобразующих единиц на пакет', N'млн. КОЕ/пакет', N'МЛН. КОЕ/ПАКЕТ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9982', N'Миллиард колониеобразующих единиц', N'млрд. КОЕ', N'МЛРД. КОЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9983', N'Протеолитическая единица', N'ПЕ', N'ПЕ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9985', N'Микрограмм на миллилитр', N'Мкг/мл', N'МКГ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9986', N'Микрограмм в сутки', N'Мкг/сут', N'МКГ/СУТ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9987', N'Микрограмм в час', N'Мкг/ч', N'МКГ/Ч', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9988', N'Микрограмм на дозу', N'Мкг/доза', N'МКГ/ДОЗА', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9990', N'Миллимоль на миллилитр', N'ммоль/мл', N'ММОЛЬ/МЛ', 17)
INSERT [OKEIUoms] ([Code], [Name], [SymbolRu], [AlphaRu], [GroupId]) VALUES (N'9991', N'Миллимоль на литр', N'ммоль/л', N'ММОЛЬ/Л', 17)


